/*
 * File: app/view/NewClientPersonWindow.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TbTrack.view.NewClientPersonWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.newClientPersonWindow',

    height: 426,
    width: 627,
    title: 'New Client Person',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'form',
                    dock: 'top',
                    frame: true,
                    height: 186,
                    layout: {
                        align: 'middle',
                        type: 'hbox'
                    },
                    bodyPadding: 10,
                    title: '',
                    dockedItems: [
                        {
                            xtype: 'container',
                            dock: 'left',
                            height: 219,
                            width: 289,
                            autoScroll: true,
                            layout: {
                                align: 'center',
                                pack: 'center',
                                type: 'vbox'
                            },
                            items: [
                                {
                                    xtype: 'combobox',
                                    width: 235,
                                    fieldLabel: 'Title'
                                },
                                {
                                    xtype: 'textfield',
                                    width: 233,
                                    fieldLabel: 'Name'
                                },
                                {
                                    xtype: 'textfield',
                                    width: 233,
                                    fieldLabel: 'Last Name'
                                },
                                {
                                    xtype: 'textfield',
                                    fieldLabel: 'Phone'
                                },
                                {
                                    xtype: 'textfield',
                                    fieldLabel: 'Fax'
                                },
                                {
                                    xtype: 'textfield',
                                    fieldLabel: 'Email'
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            dock: 'right',
                            height: 258,
                            width: 299,
                            layout: {
                                align: 'center',
                                pack: 'center',
                                type: 'vbox'
                            },
                            items: [
                                {
                                    xtype: 'combobox',
                                    width: 234,
                                    fieldLabel: 'Company'
                                },
                                {
                                    xtype: 'textfield',
                                    fieldLabel: 'P.O.'
                                },
                                {
                                    xtype: 'textfield',
                                    fieldLabel: 'Street'
                                },
                                {
                                    xtype: 'textfield',
                                    width: 233,
                                    fieldLabel: 'City / Place'
                                },
                                {
                                    xtype: 'textfield',
                                    width: 233,
                                    fieldLabel: 'Province'
                                },
                                {
                                    xtype: 'textfield',
                                    fieldLabel: 'Postal'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'textareafield',
                    dock: 'top',
                    frame: true,
                    height: 153,
                    width: 615,
                    hideLabel: true,
                    emptyText: 'Summary'
                },
                {
                    xtype: 'form',
                    dock: 'top',
                    frame: true,
                    height: 52,
                    width: 815,
                    bodyPadding: 10,
                    title: '',
                    dockedItems: [
                        {
                            xtype: 'container',
                            dock: 'right',
                            height: 40,
                            width: 225,
                            layout: {
                                align: 'middle',
                                pack: 'end',
                                type: 'hbox'
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    flex: 1,
                                    width: 194,
                                    text: 'Create'
                                },
                                {
                                    xtype: 'splitter',
                                    width: 48
                                },
                                {
                                    xtype: 'button',
                                    flex: 1,
                                    width: 194,
                                    text: 'Cancel'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});