/*
 * File: app/view/NewProjectWindow.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TbTrack.view.NewProjectWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.newProjectWindow',

    height: 560,
    width: 1073,
    layout: {
        align: 'center',
        type: 'vbox'
    },
    title: 'New Project',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'tabpanel',
                    dock: 'top',
                    height: 477,
                    activeTab: 0,
                    maxTabWidth: 100,
                    minTabWidth: 100,
                    items: [
                        {
                            xtype: 'panel',
                            layout: {
                                align: 'center',
                                type: 'vbox'
                            },
                            title: 'Basic',
                            dockedItems: [
                                {
                                    xtype: 'form',
                                    flex: 1,
                                    dock: 'top',
                                    frame: true,
                                    height: 145,
                                    layout: {
                                        align: 'middle',
                                        type: 'hbox'
                                    },
                                    bodyPadding: 10,
                                    title: '',
                                    dockedItems: [
                                        {
                                            xtype: 'container',
                                            dock: 'left',
                                            height: 219,
                                            width: 256,
                                            layout: {
                                                align: 'center',
                                                pack: 'center',
                                                type: 'vbox'
                                            },
                                            items: [
                                                {
                                                    xtype: 'textfield',
                                                    width: 241,
                                                    fieldLabel: 'File ID'
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    width: 241,
                                                    fieldLabel: 'File Name'
                                                },
                                                {
                                                    xtype: 'combobox',
                                                    width: 241,
                                                    fieldLabel: 'File Type'
                                                },
                                                {
                                                    xtype: 'combobox',
                                                    width: 240,
                                                    fieldLabel: 'Eng. Are'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'container',
                                            dock: 'left',
                                            height: 219,
                                            width: 259,
                                            layout: {
                                                align: 'center',
                                                pack: 'center',
                                                type: 'vbox'
                                            },
                                            items: [
                                                {
                                                    xtype: 'datefield',
                                                    fieldLabel: 'Creation Date'
                                                },
                                                {
                                                    xtype: 'datefield',
                                                    flex: 0,
                                                    fieldLabel: 'D. O. I.'
                                                },
                                                {
                                                    xtype: 'datefield',
                                                    fieldLabel: 'Deadline'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'container',
                                            dock: 'left',
                                            height: 258,
                                            width: 269,
                                            layout: {
                                                align: 'center',
                                                pack: 'center',
                                                type: 'vbox'
                                            },
                                            items: [
                                                {
                                                    xtype: 'combobox',
                                                    fieldLabel: 'Status'
                                                },
                                                {
                                                    xtype: 'combobox',
                                                    fieldLabel: 'Type'
                                                },
                                                {
                                                    xtype: 'combobox',
                                                    fieldLabel: 'Role'
                                                },
                                                {
                                                    xtype: 'combobox',
                                                    fieldLabel: 'Priority'
                                                },
                                                {
                                                    xtype: 'combobox',
                                                    fieldLabel: 'Low Sped'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'container',
                                            dock: 'left',
                                            height: 258,
                                            width: 263,
                                            layout: {
                                                align: 'center',
                                                pack: 'center',
                                                type: 'vbox'
                                            },
                                            items: [
                                                {
                                                    xtype: 'textfield',
                                                    width: 239,
                                                    fieldLabel: 'Suite'
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    width: 239,
                                                    fieldLabel: 'Street'
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    width: 239,
                                                    fieldLabel: 'City / Place'
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    width: 239,
                                                    fieldLabel: 'Province'
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'form',
                                    flex: 1,
                                    dock: 'top',
                                    frame: true,
                                    height: 139,
                                    width: 815,
                                    layout: {
                                        align: 'middle',
                                        type: 'hbox'
                                    },
                                    bodyPadding: 10,
                                    title: '',
                                    dockedItems: [
                                        {
                                            xtype: 'container',
                                            flex: 1,
                                            dock: 'left',
                                            height: 55,
                                            width: 266,
                                            layout: {
                                                align: 'center',
                                                pack: 'center',
                                                type: 'vbox'
                                            },
                                            items: [
                                                {
                                                    xtype: 'combobox',
                                                    flex: 0,
                                                    fieldLabel: '1st Eng'
                                                },
                                                {
                                                    xtype: 'combobox',
                                                    flex: 0,
                                                    fieldLabel: 'Current Eng'
                                                },
                                                {
                                                    xtype: 'datefield',
                                                    flex: 0,
                                                    fieldLabel: 'Trial'
                                                },
                                                {
                                                    xtype: 'datefield',
                                                    flex: 0,
                                                    fieldLabel: 'Due'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'container',
                                            flex: 1,
                                            dock: 'left',
                                            height: 55,
                                            width: 251,
                                            layout: {
                                                align: 'center',
                                                pack: 'center',
                                                type: 'vbox'
                                            },
                                            items: [
                                                {
                                                    xtype: 'textfield',
                                                    width: 239,
                                                    fieldLabel: 'Report'
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    width: 239,
                                                    fieldLabel: 'Current Budget'
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    width: 239,
                                                    fieldLabel: 'Estimate Budget'
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    width: 241,
                                                    fieldLabel: 'Warning Point'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'container',
                                            flex: 0,
                                            dock: 'left',
                                            width: 532,
                                            layout: {
                                                pack: 'center',
                                                type: 'vbox'
                                            },
                                            items: [
                                                {
                                                    xtype: 'combobox',
                                                    width: 295,
                                                    fieldLabel: 'Client'
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    width: 294,
                                                    fieldLabel: 'Client File'
                                                },
                                                {
                                                    xtype: 'textareafield',
                                                    flex: 1,
                                                    height: 71,
                                                    width: 583,
                                                    fieldLabel: 'Billing Note'
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'textareafield',
                                    dock: 'top',
                                    frame: true,
                                    height: 159,
                                    width: 1032,
                                    hideLabel: true,
                                    emptyText: 'Description'
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            title: 'Vehicles & Exhibits',
                            dockedItems: [
                                {
                                    xtype: 'container',
                                    dock: 'top',
                                    height: 33,
                                    layout: {
                                        align: 'middle',
                                        type: 'hbox'
                                    },
                                    items: [
                                        {
                                            xtype: 'displayfield',
                                            flex: 1,
                                            width: 1282,
                                            fieldLabel: 'Label',
                                            hideLabel: true,
                                            value: 'Vehicles'
                                        },
                                        {
                                            xtype: 'button',
                                            width: 78,
                                            text: 'New Vehicles'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'gridpanel',
                                    dock: 'top',
                                    height: 217,
                                    width: 1282,
                                    title: '',
                                    columns: [
                                        {
                                            xtype: 'rownumberer'
                                        },
                                        {
                                            xtype: 'datecolumn',
                                            text: 'Year'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: 127,
                                            text: 'Data'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: 110,
                                            text: 'Inspect.'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: 110,
                                            text: 'Make'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: 110,
                                            text: 'Model'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: 110,
                                            text: 'Type'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: 110,
                                            text: 'Owner'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: 110,
                                            text: 'Driver'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: 110,
                                            text: 'Insurer'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: 110,
                                            text: 'Passengers'
                                        },
                                        {
                                            xtype: 'actioncolumn',
                                            width: 145,
                                            items: [
                                                {

                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    dock: 'top',
                                    height: 33,
                                    layout: {
                                        align: 'middle',
                                        type: 'hbox'
                                    },
                                    items: [
                                        {
                                            xtype: 'displayfield',
                                            flex: 1,
                                            width: 1282,
                                            fieldLabel: 'Label',
                                            hideLabel: true,
                                            value: 'Exhibits'
                                        },
                                        {
                                            xtype: 'button',
                                            width: 78,
                                            text: 'New Exhibits'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'gridpanel',
                                    dock: 'top',
                                    height: 449,
                                    width: 1282,
                                    autoScroll: true,
                                    title: '',
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            width: 96,
                                            text: 'File'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            text: 'Status'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: 147,
                                            text: 'Name'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            text: 'Client'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            text: 'Contact'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            text: 'Description'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            width: 58,
                                            text: 'Qty'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            text: 'Received'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            text: 'Remove'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            text: 'Location'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            text: '2006 Found'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: 137,
                                            text: 'Instruction Letter Sent'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: 98,
                                            text: 'Discard'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: 98,
                                            text: 'Invoice Sent'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: 98,
                                            text: 'Payment Received'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: 98,
                                            text: 'Volume Est.'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: 98,
                                            text: 'Storage Fee'
                                        },
                                        {
                                            xtype: 'actioncolumn',
                                            width: 145,
                                            items: [
                                                {

                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            title: 'Disbursements',
                            dockedItems: [
                                {
                                    xtype: 'container',
                                    dock: 'top',
                                    height: 33,
                                    width: 1202,
                                    layout: {
                                        align: 'middle',
                                        pack: 'end',
                                        type: 'hbox'
                                    },
                                    items: [
                                        {
                                            xtype: 'button',
                                            width: 78,
                                            text: 'New'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'gridpanel',
                                    dock: 'top',
                                    height: 863,
                                    width: 1282,
                                    title: '',
                                    columns: [
                                        {
                                            xtype: 'rownumberer'
                                        },
                                        {
                                            xtype: 'datecolumn',
                                            text: 'Date'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: 96,
                                            text: 'Activity'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            text: 'Qty'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: 96,
                                            text: 'Rate / Charge'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: 96,
                                            text: 'Total'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            text: 'D/ Km'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: 401,
                                            text: 'Description'
                                        },
                                        {
                                            xtype: 'actioncolumn',
                                            width: 145,
                                            items: [
                                                {

                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'form',
                    flex: 0,
                    dock: 'top',
                    frame: true,
                    height: 52,
                    width: 815,
                    bodyPadding: 10,
                    title: '',
                    dockedItems: [
                        {
                            xtype: 'container',
                            dock: 'right',
                            height: 40,
                            itemId: 'projectCreationButtonGroup',
                            width: 271,
                            layout: {
                                align: 'middle',
                                pack: 'end',
                                type: 'hbox'
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    flex: 1,
                                    width: 194,
                                    text: 'Create'
                                },
                                {
                                    xtype: 'splitter',
                                    width: 48
                                },
                                {
                                    xtype: 'button',
                                    flex: 1,
                                    width: 194,
                                    text: 'Cancel'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});