/*
 * File: app/view/NewStaffWindow.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TbTrack.view.NewStaffWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.newStaffWindow',

    height: 423,
    width: 588,
    title: 'New Staff',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'form',
                    dock: 'top',
                    frame: true,
                    height: 104,
                    layout: {
                        align: 'middle',
                        type: 'hbox'
                    },
                    bodyPadding: 10,
                    title: '',
                    dockedItems: [
                        {
                            xtype: 'container',
                            dock: 'left',
                            height: 219,
                            width: 286,
                            layout: {
                                align: 'center',
                                pack: 'center',
                                type: 'vbox'
                            },
                            items: [
                                {
                                    xtype: 'combobox',
                                    width: 240,
                                    fieldLabel: 'Title'
                                },
                                {
                                    xtype: 'textfield',
                                    width: 241,
                                    fieldLabel: 'First Name'
                                },
                                {
                                    xtype: 'textfield',
                                    width: 241,
                                    fieldLabel: 'Last Name'
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            dock: 'left',
                            height: 219,
                            width: 293,
                            layout: {
                                align: 'center',
                                pack: 'center',
                                type: 'vbox'
                            },
                            items: [
                                {
                                    xtype: 'combobox',
                                    width: 241,
                                    fieldLabel: 'Position'
                                },
                                {
                                    xtype: 'combobox',
                                    fieldLabel: 'Status'
                                },
                                {
                                    xtype: 'datefield',
                                    fieldLabel: 'Start Date'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'form',
                    dock: 'top',
                    frame: true,
                    height: 123,
                    width: 815,
                    layout: {
                        align: 'middle',
                        type: 'hbox'
                    },
                    bodyPadding: 10,
                    title: '',
                    dockedItems: [
                        {
                            xtype: 'container',
                            dock: 'left',
                            height: 258,
                            width: 280,
                            layout: {
                                align: 'center',
                                pack: 'center',
                                type: 'vbox'
                            },
                            items: [
                                {
                                    xtype: 'textfield',
                                    width: 239,
                                    fieldLabel: 'Rate'
                                },
                                {
                                    xtype: 'textfield',
                                    width: 239,
                                    fieldLabel: 'Salary'
                                },
                                {
                                    xtype: 'combobox',
                                    fieldLabel: 'Role'
                                },
                                {
                                    xtype: 'combobox',
                                    fieldLabel: 'Active'
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            dock: 'left',
                            height: 258,
                            width: 301,
                            layout: {
                                align: 'center',
                                pack: 'center',
                                type: 'vbox'
                            },
                            items: [
                                {
                                    xtype: 'textfield',
                                    width: 239,
                                    fieldLabel: 'Suite'
                                },
                                {
                                    xtype: 'textfield',
                                    width: 239,
                                    fieldLabel: 'Street'
                                },
                                {
                                    xtype: 'textfield',
                                    width: 239,
                                    fieldLabel: 'City / Place'
                                },
                                {
                                    xtype: 'textfield',
                                    width: 239,
                                    fieldLabel: 'Province'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'textareafield',
                    dock: 'top',
                    frame: true,
                    height: 112,
                    width: 576,
                    hideLabel: true,
                    emptyText: 'Description'
                },
                {
                    xtype: 'form',
                    dock: 'top',
                    frame: true,
                    height: 52,
                    width: 815,
                    bodyPadding: 10,
                    title: '',
                    dockedItems: [
                        {
                            xtype: 'container',
                            dock: 'right',
                            height: 40,
                            itemId: 'projectEditButtonGroup',
                            width: 208,
                            layout: {
                                align: 'middle',
                                pack: 'center',
                                type: 'hbox'
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    flex: 1,
                                    width: 194,
                                    text: 'Create'
                                },
                                {
                                    xtype: 'splitter',
                                    width: 48
                                },
                                {
                                    xtype: 'button',
                                    flex: 1,
                                    width: 194,
                                    text: 'Cancel'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});