/*
 * File: app/view/ProjectListView.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TbTrack.view.ProjectListView', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.projectListView',

    height: 594,
    autoScroll: true,
    title: 'Project',
    columnLines: true,
    enableColumnHide: false,
    enableColumnMove: false,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            columns: [
                {
                    xtype: 'rownumberer',
                    width: 50,
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'file',
                    text: 'File ID'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'name',
                    text: 'File Name'
                },
                {
                    xtype: 'datecolumn',
                    dataIndex: 'date',
                    text: 'Creation Date'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'firstEngineerID',
                    text: '1st Eng ID'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'firstEngineer',
                    text: '1st Eng Initial'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'currentEngineerID',
                    text: 'Curr Eng ID'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'currentEngineer',
                    text: 'Curr Eng ID'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'clashCheckStaffID',
                    text: 'Clash Check Staff ID'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'clashCheckStaff',
                    text: 'Clash Check Staff Initial'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'client',
                    text: 'Client'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'contact',
                    text: 'Contact'
                },
                {
                    xtype: 'gridcolumn',
                    text: 'Priority'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'code',
                    text: 'Status'
                },
                {
                    xtype: 'gridcolumn',
                    text: 'Current Budget'
                },
                {
                    xtype: 'gridcolumn',
                    text: 'Estimate Budget'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'notes',
                    width: 409,
                    text: 'Description'
                }
            ]
        });

		//renderTo: Ext.getBody();
       	me.callParent(arguments);
    }

});