/*
 * File: app/view/StaffInfo.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TbTrack.view.StaffInfo', {
    extend: 'Ext.tab.Panel',
    alias: 'widget.staffInfo',

    height: 765,
    width: 1059,
    activeTab: 0,
    maxTabWidth: 100,
    minTabWidth: 100,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    layout: {
                        align: 'center',
                        type: 'vbox'
                    },
                    title: 'Basic',
                    dockedItems: [
                        {
                            xtype: 'form',
                            flex: 1,
                            dock: 'top',
                            frame: true,
                            height: 145,
                            layout: {
                                align: 'middle',
                                type: 'hbox'
                            },
                            bodyPadding: 10,
                            title: '',
                            dockedItems: [
                                {
                                    xtype: 'container',
                                    dock: 'left',
                                    height: 219,
                                    width: 506,
                                    layout: {
                                        align: 'center',
                                        pack: 'center',
                                        type: 'vbox'
                                    },
                                    items: [
                                        {
                                            xtype: 'combobox',
                                            width: 240,
                                            fieldLabel: 'Title'
                                        },
                                        {
                                            xtype: 'textfield',
                                            width: 241,
                                            fieldLabel: 'First Name'
                                        },
                                        {
                                            xtype: 'textfield',
                                            width: 241,
                                            fieldLabel: 'Last Name'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    dock: 'left',
                                    height: 219,
                                    width: 450,
                                    layout: {
                                        align: 'center',
                                        pack: 'center',
                                        type: 'vbox'
                                    },
                                    items: [
                                        {
                                            xtype: 'combobox',
                                            width: 241,
                                            fieldLabel: 'Position'
                                        },
                                        {
                                            xtype: 'combobox',
                                            fieldLabel: 'Status'
                                        },
                                        {
                                            xtype: 'datefield',
                                            fieldLabel: 'Start Date'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'form',
                            flex: 1,
                            dock: 'top',
                            frame: true,
                            height: 139,
                            width: 815,
                            layout: {
                                align: 'middle',
                                type: 'hbox'
                            },
                            bodyPadding: 10,
                            title: '',
                            dockedItems: [
                                {
                                    xtype: 'container',
                                    dock: 'left',
                                    height: 258,
                                    width: 500,
                                    layout: {
                                        align: 'center',
                                        pack: 'center',
                                        type: 'vbox'
                                    },
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            width: 239,
                                            fieldLabel: 'Salary'
                                        },
                                        {
                                            xtype: 'textfield',
                                            width: 239,
                                            fieldLabel: 'Rate'
                                        },
                                        {
                                            xtype: 'combobox',
                                            fieldLabel: 'Role'
                                        },
                                        {
                                            xtype: 'combobox',
                                            fieldLabel: 'Active'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    dock: 'left',
                                    height: 258,
                                    width: 452,
                                    layout: {
                                        align: 'center',
                                        pack: 'center',
                                        type: 'vbox'
                                    },
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            width: 239,
                                            fieldLabel: 'Suite'
                                        },
                                        {
                                            xtype: 'textfield',
                                            width: 239,
                                            fieldLabel: 'Street'
                                        },
                                        {
                                            xtype: 'textfield',
                                            width: 239,
                                            fieldLabel: 'City / Place'
                                        },
                                        {
                                            xtype: 'textfield',
                                            width: 239,
                                            fieldLabel: 'Province'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'form',
                            flex: 1,
                            dock: 'bottom',
                            frame: true,
                            height: 52,
                            width: 815,
                            bodyPadding: 10,
                            title: '',
                            dockedItems: [
                                {
                                    xtype: 'container',
                                    dock: 'right',
                                    height: 40,
                                    itemId: 'projectEditButtonGroup',
                                    width: 339,
                                    layout: {
                                        align: 'middle',
                                        pack: 'center',
                                        type: 'hbox'
                                    },
                                    items: [
                                        {
                                            xtype: 'button',
                                            flex: 1,
                                            width: 194,
                                            text: 'Update'
                                        },
                                        {
                                            xtype: 'splitter',
                                            width: 48
                                        },
                                        {
                                            xtype: 'button',
                                            flex: 1,
                                            width: 194,
                                            text: 'Delete'
                                        },
                                        {
                                            xtype: 'splitter',
                                            width: 48
                                        },
                                        {
                                            xtype: 'button',
                                            flex: 1,
                                            width: 194,
                                            text: 'Cancel'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'gridpanel',
                            flex: 1,
                            dock: 'bottom',
                            height: 297,
                            title: 'Notes',
                            columns: [
                                {
                                    xtype: 'datecolumn',
                                    dataIndex: 'date',
                                    text: 'Date'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 637,
                                    dataIndex: 'string',
                                    text: 'Project Note'
                                },
                                {
                                    xtype: 'datecolumn',
                                    text: 'Appointment'
                                },
                                {
                                    xtype: 'datecolumn',
                                    text: 'Due Date'
                                },
                                {
                                    xtype: 'actioncolumn',
                                    width: 151,
                                    items: [
                                        {

                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'textareafield',
                            flex: 1,
                            dock: 'top',
                            frame: true,
                            height: 102,
                            width: 1041,
                            hideLabel: true,
                            emptyText: 'Description'
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    layout: {
                        type: 'anchor'
                    },
                    title: 'Work Track',
                    dockedItems: [
                        {
                            xtype: 'container',
                            dock: 'top',
                            height: 33,
                            width: 1202,
                            layout: {
                                align: 'middle',
                                pack: 'end',
                                type: 'hbox'
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    width: 78,
                                    text: 'New'
                                }
                            ]
                        },
                        {
                            xtype: 'gridpanel',
                            dock: 'top',
                            height: 863,
                            width: 1282,
                            title: '',
                            columns: [
                                {
                                    xtype: 'datecolumn',
                                    text: 'Date'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 96,
                                    text: 'Activity'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 499,
                                    text: 'Description'
                                },
                                {
                                    xtype: 'numbercolumn',
                                    dataIndex: 'number',
                                    text: 'Start time'
                                },
                                {
                                    xtype: 'numbercolumn',
                                    dataIndex: 'number',
                                    text: 'End time'
                                },
                                {
                                    xtype: 'numbercolumn',
                                    dataIndex: 'number',
                                    text: 'Total time'
                                },
                                {
                                    xtype: 'actioncolumn',
                                    width: 145,
                                    items: [
                                        {

                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    title: 'Billing',
                    dockedItems: [
                        {
                            xtype: 'gridpanel',
                            dock: 'top',
                            height: 863,
                            width: 1282,
                            title: '',
                            columns: [
                                {
                                    xtype: 'gridcolumn',
                                    width: 96,
                                    text: 'Eng'
                                },
                                {
                                    xtype: 'datecolumn',
                                    text: 'Date'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 96,
                                    text: 'Activity'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 96,
                                    text: 'Type'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 322,
                                    text: 'Description'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 96,
                                    text: 'Qty'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 96,
                                    text: 'Rate'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 96,
                                    text: 'Charge'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 96,
                                    text: 'Dis. Qty'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 96,
                                    text: 'Dis. Rate'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 96,
                                    text: 'Final Charge'
                                },
                                {
                                    xtype: 'actioncolumn',
                                    width: 145,
                                    items: [
                                        {

                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});