/*
 * File: app/view/TodoListView.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TbTrack.view.TodoListView', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.todoListView',

    height: 594,
    autoScroll: true,
    title: 'To-do',
    columnLines: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            columns: [
                {
                    xtype: 'rownumberer'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'string',
                    text: 'Name'
                },
                {
                    xtype: 'datecolumn',
                    dataIndex: 'date',
                    text: 'Creation Date'
                },
                {
                    xtype: 'datecolumn',
                    text: 'Reminder'
                },
                {
                    xtype: 'datecolumn',
                    text: 'Deadline'
                },
                {
                    xtype: 'booleancolumn',
                    dataIndex: 'bool',
                    text: 'Share',
                    editor: {
                        xtype: 'combobox'
                    }
                },
                {
                    xtype: 'gridcolumn',
                    text: 'Priority',
                    editor: {
                        xtype: 'combobox'
                    }
                },
                {
                    xtype: 'gridcolumn',
                    text: 'Status'
                },
                {
                    xtype: 'gridcolumn',
                    width: 332,
                    text: 'Description'
                }
            ]
        });

        me.callParent(arguments);
    }

});