/*
 * File: app/controller/LoginController.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TbTrack.controller.LoginController', {
    extend: 'Ext.app.Controller',
    views: [
        'Login',
        'Main'
    ],
    refs: [
        {
            autoCreate: true,
            ref: 'login',
            selector: 'login',
            xtype: 'login'
        },
        {
            autoCreate: true,
            ref: 'main',
            selector: 'main',
            xtype: 'main'
        }
    ],
    loginButtonClick: function(button, e, eOpts) {
        var username = Ext.getCmp('usernameField').getValue(),
             password = Ext.getCmp('passwordField').getValue();

        this.setMask('loginPanel', true);
        Ext.Ajax.request({
            useDefaultXhrHeader: false,
            url: 'http://192.168.1.71:8080/RestfulAPI/index.php',
            method: "POST",
            scope: this,
            headers: {
                'Content-Type': 'application/x-www-form-urlencoded',
                'Accept': 'text/html,application/json'
            },
            params: {
                method: "login",
                format: "json",
                username: username,
                password: password
            },
            callback: function(options, success, response) {
                this.setMask('loginPanel', false);
                if (success) {
                    var result = JSON.parse(response.responseText);
                    console.log(result); // Debug
                    if (result.data === 'FALSE') {
                        alert('Unvalid username and password combination, please try again');
                    } else {
                        alert('Login succeed');
                        this.getLogin().destroy();
                        this.getMain();
                    }
                } else {

                }
            }
        });

    },
    init: function(application) {
        this.control({
            "login #loginButton": {
                click: this.loginButtonClick
            }
        });
    },
    setMask: function(viewportId, flag) {
        Ext.getCmp(viewportId).setLoading(flag);
    }
});
